/**
 * This file is auto-generated by backend/src/core.ts during vite server startup don't edit this file for any reason
*/

import React from "react";
import { Route, Routes } from "react-router";
import loadable from "@loadable/component";

const AppRouter=()=><Routes></Routes>;export default AppRouter
