/**
 * This file is auto-generated by backend/src/core.ts during vite server startup don't edit this file for any reason
*/

import loadable from "@loadable/component";
import React from "react";
import { Route, Routes } from "react-router";


const Application0=loadable(()=>import("@yourdash/applications/uk-ewsgit-dash/web/index.tsx"));const Application1=loadable(()=>import("@yourdash/applications/uk-ewsgit-files/web/index.tsx"));const Application2=loadable(()=>import("@yourdash/applications/uk-ewsgit-photos/web/index.tsx"));const Application3=loadable(()=>import("@yourdash/applications/uk-ewsgit-weather/web/index.tsx"));const Application4=loadable(()=>import("@yourdash/applications/uk-ewsgit-store/web/index.tsx"));const Application5=loadable(()=>import("@yourdash/applications/uk-ewsgit-settings/web/index.tsx"));const Application6=loadable(()=>import("@yourdash/applications/uk-ewsgit-nextcloud/web/index.tsx"));const AppRouter=()=><Routes><Route path={"uk-ewsgit-dash/*"} element={<Application0/>}/><Route path={"uk-ewsgit-files/*"} element={<Application1/>}/><Route path={"uk-ewsgit-photos/*"} element={<Application2/>}/><Route path={"uk-ewsgit-weather/*"} element={<Application3/>}/><Route path={"uk-ewsgit-store/*"} element={<Application4/>}/><Route path={"uk-ewsgit-settings/*"} element={<Application5/>}/><Route path={"uk-ewsgit-nextcloud/*"} element={<Application6/>}/></Routes>;export default AppRouter
