services:
  web:
    depends_on:
      backend:
        condition: "service_started"
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: web-release
    restart: always
    ports:
      - "5173:5173"
    hostname: yourdash.localhost
    container_name: "yourdash_web"
    develop:
      watch:
        - action: sync
          path: ./instance/web/src/
          target: /web/src/
          ignore:
            - node_modules/
        - action: sync
          path: ./apps/
          target: /web/src/app/apps/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./instance/web/package.json
        - action: sync+restart
          path: ./instance/web/vite.config.ts
          target: /web/vite.config.ts
        - action: sync+restart
          path: ./instance/web/tsconfig.json
          target: /web/tsconfig.json
        - action: sync+restart
          path: ./instance/web/tsconfig.node.json
          target: /web/tsconfig.node.json
    environment:
      - VITE_IS_DOCKER=true
      - VITE_INSTANCE_BACKEND_URL=http://localhost:3563

  backend:
    depends_on:
      postgres:
        condition: "service_healthy"
        required: true
    container_name: "yourdash_backend"
    ports:
      - "3563:3563"
    hostname: yourdash_backend.localhost
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: backend-release
    volumes:
      - ./fs:/fs/
    restart: always
    develop:
      watch:
        - action: sync+restart
          path: ./instance/backend/
          target: /backend/
          ignore:
            - node_modules/
        - action: sync+restart
          path: ./apps/
          target: /backend/apps/
          ignore:
            - node_modules/
    environment:
      - IS_DOCKER=true

  postgres:
    container_name: "yourdash_postgres"
    image: "postgres"
    shm_size: 128mb
    hostname: yourdash_postgres.localhost
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - yourdash-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  yourdash-postgres-data: