import type { UKDesignTheme } from "../theme.ts";
import { uk } from "../tokens.ts";

const baselineTheme: UKDesignTheme = {
    ref: {
        palette: {
            error0: () => "#000000ff",
            error10: () => "#410e0bff",
            error20: () => "#601410ff",
            error30: () => "#8c1d18ff",
            error40: () => "#b3261eff",
            error50: () => "#dc362eff",
            error60: () => "#e46962ff",
            error70: () => "#ec928eff",
            error80: () => "#f2b8b5ff",
            error90: () => "#f9dedcff",
            error95: () => "#fceeeeff",
            error99: () => "#fffbf9ff",
            error100: () => "#ffffffff",
            tertiary0: () => "#000000ff",
            tertiary10: () => "#31111dff",
            tertiary20: () => "#492532ff",
            tertiary30: () => "#633b48ff",
            tertiary40: () => "#7d5260ff",
            tertiary50: () => "#986977ff",
            tertiary60: () => "#b58392ff",
            tertiary70: () => "#d29dacff",
            tertiary80: () => "#efb8c8ff",
            tertiary90: () => "#ffd8e4ff",
            tertiary95: () => "#ffecf1ff",
            tertiary99: () => "#fffbfaff",
            tertiary100: () => "#ffffffff",
            secondary0: () => "#000000ff",
            secondary10: () => "#1d192bff",
            secondary20: () => "#332d41ff",
            secondary30: () => "#4a4458ff",
            secondary40: () => "#625b71ff",
            secondary50: () => "#7a7289ff",
            secondary60: () => "#958da5ff",
            secondary70: () => "#b0a7c0ff",
            secondary80: () => "#ccc2dcff",
            secondary90: () => "#e8def8ff",
            secondary95: () => "#f6edffff",
            secondary99: () => "#fffbfeff",
            secondary100: () => "#ffffffff",
            primary0: () => "#000000ff",
            primary10: () => "#21005dff",
            primary20: () => "#381e72ff",
            primary30: () => "#4f378bff",
            primary40: () => "#6750a4ff",
            primary50: () => "#7f67beff",
            primary60: () => "#9a82dbff",
            primary70: () => "#b69df8ff",
            primary80: () => "#d0bcffff",
            primary90: () => "#eaddffff",
            primary95: () => "#f6edffff",
            primary99: () => "#fffbfeff",
            primary100: () => "#ffffffff",
            "neutral-variant0": () => "#000000ff",
            "neutral-variant10": () => "#1d1a22ff",
            "neutral-variant20": () => "#322f37ff",
            "neutral-variant30": () => "#49454fff",
            "neutral-variant40": () => "#605d66ff",
            "neutral-variant50": () => "#79747eff",
            "neutral-variant60": () => "#938f99ff",
            "neutral-variant70": () => "#aea9b4ff",
            "neutral-variant80": () => "#cac4d0ff",
            "neutral-variant90": () => "#e7e0ecff",
            "neutral-variant95": () => "#f5eefaff",
            "neutral-variant99": () => "#fffbfeff",
            "neutral-variant100": () => "#ffffffff",
            neutral0: () => "#000000ff",
            neutral10: () => "#1c1b1fff",
            neutral12: () => "#211F26ff",
            neutral20: () => "#313033ff",
            neutral22: () => "#36343Bff",
            neutral30: () => "#484649ff",
            neutral40: () => "#605d62ff",
            neutral50: () => "#787579ff",
            neutral60: () => "#939094ff",
            neutral70: () => "#aeaaaeff",
            neutral80: () => "#c9c5caff",
            neutral90: () => "#e6e1e5ff",
            neutral94: () => "#F3EDF7ff",
            neutral95: () => "#f4eff4ff",
            neutral99: () => "#fffbfeff",
            neutral100: () => "#ffffffff",
            black: () => "#000000ff",
            white: () => "#ffffffff",
        },
        typeface: {
            plain: () => "Roboto",
            brand: () => "Roboto",
            "weight-bold": () => "700",
            "weight-medium": () => "500",
            "weight-regular": () => "400",
        },
    },
    sys: {
        color: {
            lightMode: {
                "surface-tint": () => uk.raw.sys.color.lightMode.primary(),
                "surface-tint-color": () => uk.raw.sys.color.lightMode.primary(),
                "on-error-container": () => uk.raw.ref.palette.error10(),
                "on-error": () => uk.raw.ref.palette.error100(),
                "error-container": () => uk.raw.ref.palette.error90(),
                "on-tertiary-container": () => uk.raw.ref.palette.tertiary10(),
                "on-tertiary": () => uk.raw.ref.palette.tertiary100(),
                "tertiary-container": () => uk.raw.ref.palette.tertiary90(),
                tertiary: () => uk.raw.ref.palette.tertiary40(),
                shadow: () => uk.raw.ref.palette.neutral0(),
                error: () => uk.raw.ref.palette.error40(),
                outline: () => uk.raw.ref.palette["neutral-variant50"](),
                "outline-variant": () => uk.raw.ref.palette["neutral-variant80"](),
                "on-background": () => uk.raw.ref.palette.neutral10(),
                background: () => uk.raw.ref.palette.neutral99(),
                "inverse-on-surface": () => uk.raw.ref.palette.neutral95(),
                "inverse-surface": () => uk.raw.ref.palette.neutral20(),
                "on-surface-variant": () => uk.raw.ref.palette["neutral-variant30"](),
                "on-surface": () => uk.raw.ref.palette.neutral10(),
                "surface-variant": () => uk.raw.ref.palette["neutral-variant90"](),
                surface: () => uk.raw.ref.palette.neutral99(),
                "surface-container": () => uk.raw.ref.palette.neutral94(),
                "surface-container-highest": () => uk.raw.ref.palette.neutral90(),
                "on-secondary-container": () => uk.raw.ref.palette.secondary10(),
                "on-secondary": () => uk.raw.ref.palette.secondary100(),
                "secondary-container": () => uk.raw.ref.palette.secondary90(),
                secondary: () => uk.raw.ref.palette.secondary40(),
                "inverse-primary": () => uk.raw.ref.palette.primary80(),
                "on-primary-container": () => uk.raw.ref.palette.primary10(),
                "on-primary": () => uk.raw.ref.palette.primary100(),
                "primary-container": () => uk.raw.ref.palette.primary90(),
                primary: () => uk.raw.ref.palette.primary40(),
            },
            darkMode: {
                "surface-tint": () => uk.raw.sys.color.darkMode.primary(),
                "surface-tint-color": () => uk.raw.sys.color.darkMode.primary(),
                "on-error-container": () => uk.raw.ref.palette.error80(),
                "on-error": () => uk.raw.ref.palette.error20(),
                "error-container": () => uk.raw.ref.palette.error30(),
                "on-tertiary-container": () => uk.raw.ref.palette.tertiary90(),
                "on-tertiary": () => uk.raw.ref.palette.tertiary20(),
                "tertiary-container": () => uk.raw.ref.palette.tertiary30(),
                tertiary: () => uk.raw.ref.palette.tertiary80(),
                shadow: () => uk.raw.ref.palette.neutral0(),
                error: () => uk.raw.ref.palette.error80(),
                outline: () => uk.raw.ref.palette["neutral-variant60"](),
                "outline-variant": () => uk.raw.ref.palette["neutral-variant30"](),
                "on-background": () => uk.raw.ref.palette.neutral90(),
                background: () => uk.raw.ref.palette.neutral10(),
                "inverse-on-surface": () => uk.raw.ref.palette.neutral20(),
                "inverse-surface": () => uk.raw.ref.palette.neutral90(),
                "on-surface-variant": () => uk.raw.ref.palette["neutral-variant80"](),
                "on-surface": () => uk.raw.ref.palette.neutral90(),
                "surface-variant": () => uk.raw.ref.palette["neutral-variant30"](),
                surface: () => uk.raw.ref.palette.neutral10(),
                "surface-container": () => uk.raw.ref.palette.neutral12(),
                "surface-container-highest": () => uk.raw.ref.palette.neutral22(),
                "on-secondary-container": () => uk.raw.ref.palette.secondary90(),
                "on-secondary": () => uk.raw.ref.palette.secondary20(),
                "secondary-container": () => uk.raw.ref.palette.secondary30(),
                secondary: () => uk.raw.ref.palette.secondary80(),
                "inverse-primary": () => uk.raw.ref.palette.primary40(),
                "on-primary-container": () => uk.raw.ref.palette.primary90(),
                "on-primary": () => uk.raw.ref.palette.primary20(),
                "primary-container": () => uk.raw.ref.palette.primary30(),
                primary: () => uk.raw.ref.palette.primary80(),
            },
        },
    },
};

export { baselineTheme };
