name: Build and Deploy to https://ydsh.pages.dev and https://yourdash.pages.dev

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.7.1]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.0.11 # or "latest"

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build website
        run: (cd ./packages/web && bun run build)

      - name: Deploy to "yourdash.ewsgit.uk" and "yourdash.github.io"
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: packages/web/dist/
          destination-github-username: yourdash-app
          destination-repository-name: "yourdash-app.github.io"
          user-email: ewsgit@duck.com
          target-branch: main

      - name: Deploy to "ydsh.ewsgit.uk" and "yourdash.github.io/yourdash"
        uses: moodiest/push-to-branch-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: packages/web/dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
